# Hadolint configuration for Dockerfile linting
# https://github.com/hadolint/hadolint

# Ignore specific rules
ignored:
  # DL3008: Pin versions in apt-get install
  # - DL3008
  
  # DL3018: Pin versions in apk add
  # - DL3018
  
  # DL3059: Multiple consecutive RUN instructions
  # - DL3059

# Configure trusted registries
trustedRegistries:
  - docker.io
  - docker.elastic.co

# Override error level for specific rules
override:
  error:
    - DL3001  # Use JSON array format for CMD
    - DL3002  # Last USER should not be root
    - DL3020  # Use COPY instead of ADD
    - DL3025  # Use JSON array format for CMD
  warning:
    - DL3008  # Pin versions in apt-get install
    - DL3009  # Delete the apt-get lists after installing
    - DL3015  # Avoid additional packages by specifying --no-install-recommends
    - DL3018  # Pin versions in apk add
  info:
    - DL3013  # Pin versions in pip
  style:
    - DL3003  # Use WORKDIR to switch to a directory

# Inline ignore comments
# Use this format in Dockerfiles: # hadolint ignore=DL3003,DL3006
